name: lint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check init.el snippets'
